sudo: required
services: 
    - docker
before_install:
    - docker build -t atparte1/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true atparte1/react-test npm run test -- --coverage
after_success:
    - docker build -t atparte1/multi-client ./client
    - docker build -t atparte1/multi-nginx ./nginx
    - docker build -t atparte1/multi-server ./server
    - docker build -t atparte1/multi-worker ./worker
#LOG IN TO DOCKER cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take images and push them to docker hub
    - docker push atparte1/multi-client
    - docker push atparte1/multi-nginx
    - docker push atparte1/multi-server
    - docker push atparte1/multi-worker
